### ISSUE TITLE
Still have fatal error

### ISSUE THREAD

**Issue by kenny-nt** [crstauf/query-monitor-extend#41]
```
2021-12-29T20:50:16+00:00 CRITICAL Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /public_html/wp-content/plugins/query-monitor-extend/collectors/image_sizes.php:133
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(305): QMX_Collector_Image_Sizes->filter__wp_get_attachment_image_src()
#1 /public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /public_html/wp-includes/media.php(991): apply_filters()
#3 /public_html/wp-includes/media.php(1131): wp_get_attachment_image_src()
#4 /public_html/wp-includes/general-template.php(936): wp_get_attachment_image_url()
#5 /public_html/wp-includes/general-template.php(977): get_site_icon_url()
#6 /public_html/wp-includes/general-template.php(3223): has_site_icon()
#7 /public_html/wp-includes/class-wp-hook.php(303): wp_site_icon()
#8 /public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#9 /public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#10 /public_html/wp-includes/general-template.php(3015): do_action()
#11 /public_html/wp-content/themes/flatsome/header.php(10): wp_head()
#12 /public_html/wp-includes/template.php(770): require_once('...')
#13 /public_html/wp-includes/template.php(716): load_template()
#14 /public_html/wp-includes/general-template.php(48): locate_template()
#15 /public_html/wp-content/themes/flatsome/page-transparent-header-light.php(5): get_header()
#16 /public_html/wp-includes/template-loader.php(106): include('...')
#17 /public_html/wp-blog-header.php(19): require_once('...')
#18 /public_html/index.php(17): require('...')
#19 {main}
  thrown in /public_html/wp-content/plugins/query-monitor-extend/collectors/image_sizes.php on line 133
```
General System Status:
Web Server: LiteSpeed Enterprise
PHP: LSPHP8.0
Themes: Flatsome
Latest WP, latest Woocommerce
Image Sizes:
```
thumbnail: 150×150 pixels (cropped to fit)
medium: 400×400 pixels (proportionally resized to fit inside dimensions)
medium_large: 768×0 pixels (proportionally resized to fit inside dimensions)
large: 0×0 pixels (proportionally resized to fit inside dimensions)
1536x1536: 1536×1536 pixels (proportionally resized to fit inside dimensions)
2048x2048: 2048×2048 pixels (proportionally resized to fit inside dimensions)
woocommerce_thumbnail: 400×400 pixels (proportionally resized to fit inside dimensions)
woocommerce_single: 768×0 pixels (proportionally resized to fit inside dimensions)
woocommerce_gallery_thumbnail: 150×150 pixels (cropped to fit)
shop_catalog: 400×400 pixels (proportionally resized to fit inside dimensions)
shop_single: 768×0 pixels (proportionally resized to fit inside dimensions)
shop_thumbnail: 150×150 pixels (cropped to fit)
```

**Comment by crstauf** [comment]
@khanh-nt Please do not submit multiple tickets for the same issue: issue #35 is open and waiting for response from you.
