### ISSUE TITLE
PHP Errors dose not show instead throws an error

### ISSUE THREAD

**Issue by varunsridharan** [crstauf/query-monitor-extend#6]
I am using Query Monitor & Query Mointor Extended in my localhost . since Query Monitor 3.0 the query monitor extended is not showing php notices in debug bar. instead it just shows like below
![image](https://user-images.githubusercontent.com/1884287/48391145-4e6a4f00-e72b-11e8-8862-9c69fd1bde38.png)

**Comment by varunsridharan** [comment]
Created A Pull Request #7

**Comment by crstauf** [comment]
@varunsridharan Will you please try [version 1.0](https://github.com/crstauf/query-monitor-extend/tree/version/1.0) (in beta), and let me know if you've the same issue?

**Comment by varunsridharan** [comment]
@crstauf 
Sure i did tried to use the V1.0 but i got the below errors in debug.log

```
[18-Nov-2018 00:44:57 UTC] PHP Notice:  Trying to get property of non-object in E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\collectors\files.php on line 23
[18-Nov-2018 00:44:57 UTC] PHP Stack trace:
[18-Nov-2018 00:44:57 UTC] PHP   1. shutdown_action_hook() E:\localhost\www\wp-frameworks\wponion\wp-includes\load.php:0
[18-Nov-2018 00:44:57 UTC] PHP   2. do_action() E:\localhost\www\wp-frameworks\wponion\wp-includes\load.php:679
[18-Nov-2018 00:44:57 UTC] PHP   3. WP_Hook->do_action() E:\localhost\www\wp-frameworks\wponion\wp-includes\plugin.php:453
[18-Nov-2018 00:44:57 UTC] PHP   4. WP_Hook->apply_filters() E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php:310
[18-Nov-2018 00:44:57 UTC] PHP   5. QM_Dispatcher_Html->dispatch() E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php:286
[18-Nov-2018 00:44:57 UTC] PHP   6. QM_Dispatcher_Html->before_output() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\dispatchers\Html.php:190
[18-Nov-2018 00:44:57 UTC] PHP   7. QM_Dispatcher_Html->get_outputters() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\dispatchers\Html.php:226
[18-Nov-2018 00:44:57 UTC] PHP   8. QM_Collectors->process() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\classes\Dispatcher.php:44
[18-Nov-2018 00:44:57 UTC] PHP   9. QMX_Collector_Files->process() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\classes\Collectors.php:53
[18-Nov-2018 00:44:57 UTC] PHP Notice:  Trying to get property of non-object in E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\collectors\files.php on line 23
[18-Nov-2018 00:44:57 UTC] PHP Stack trace:
[18-Nov-2018 00:44:57 UTC] PHP   1. shutdown_action_hook() E:\localhost\www\wp-frameworks\wponion\wp-includes\load.php:0
[18-Nov-2018 00:44:57 UTC] PHP   2. do_action() E:\localhost\www\wp-frameworks\wponion\wp-includes\load.php:679
[18-Nov-2018 00:44:57 UTC] PHP   3. WP_Hook->do_action() E:\localhost\www\wp-frameworks\wponion\wp-includes\plugin.php:453
[18-Nov-2018 00:44:57 UTC] PHP   4. WP_Hook->apply_filters() E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php:310
[18-Nov-2018 00:44:57 UTC] PHP   5. QM_Dispatcher_Html->dispatch() E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php:286
[18-Nov-2018 00:44:57 UTC] PHP   6. QM_Dispatcher_Html->before_output() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\dispatchers\Html.php:190
[18-Nov-2018 00:44:57 UTC] PHP   7. QM_Dispatcher_Html->get_outputters() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\dispatchers\Html.php:226
[18-Nov-2018 00:44:57 UTC] PHP   8. QM_Collectors->process() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\classes\Dispatcher.php:44
[18-Nov-2018 00:44:57 UTC] PHP   9. QMX_Collector_Files->process() E:\localhost\www\wp-template\wp-content\plugins\query-monitor\classes\Collectors.php:53
[18-Nov-2018 00:44:57 UTC] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\collectors\time.php:35
Stack trace:
#0 E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\collectors\time.php(35): DateTimeZone->__construct('')
#1 E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\output\html\time.php(26): QMX_Collector_Time->get_server()
#2 E:\localhost\www\wp-template\wp-content\plugins\query-monitor\dispatchers\Html.php(201): QMX_Output_Html_Time->output()
#3 E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php(286): QM_Dispatcher_Html->dispatch('')
#4 E:\localhost\www\wp-frameworks\wponion\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 E:\localhost\www\wp-frameworks\wponion\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#6 E:\localhost\www\wp-frameworks\wponion\wp-includes\load.php(679): do_action('shutdown')
#7 [internal function]: s in E:\localhost\www\wp-template\wp-content\plugins\query-monitor-extend-master\collectors\time.php on line 35
```

And here what it looked like
![image](https://user-images.githubusercontent.com/1884287/48667355-c1900e80-eaf9-11e8-92b3-4278c6be79f1.png)

https://s.svarun.in/F6

**Comment by crstauf** [comment]
Thanks, @varunsridharan; will you please try [the `issue/6` branch](https://github.com/crstauf/query-monitor-extend/tree/issue/6)? Should resolve all the errors provided in [your last comment](https://github.com/crstauf/query-monitor-extend/issues/6#issuecomment-439658719).

**Comment by varunsridharan** [comment]
@crstauf yea issue/6 branch dose fixes all the issues i reported. thanks :-)

**Comment by crstauf** [comment]
@varunsridharan Closed by https://github.com/crstauf/query-monitor-extend/commit/b431ad4afc681013083320c82eac17c91b0d0bb2.
